server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    non-secure-port: ${server.port}
    metadata-map:
      management.context-path: /admin

security:
  basic:
    enabled: false

info:
 stage: step16-solution
 topic: Circuit Breaker
 service: turbine-server
 version: 1.3
management:
  context-path: /admin

