server:
  port: 52000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

swagger:
  enabled: true
  contact-email: guenoun.y@sfeir.com
  contact-name: Youssef Guenoun
  security:
    enabled: false
  enable-try-out-methods: true
  include-patterns: ^(?!.*admin).*$

management:
  context-path: /admin

feign.hystrix.enabled: true
#hystrix.shareSecurityContext: true
#hystrix.command.default.execution.isolation.thread.timoutInMilliseconds: 10000

security:
  basic:
    enabled: false

info:
 stage: step14-solution
 topic: discovery and registry
 service: store-service
 version: 1.1

stock-service.name: stock-service

sales-service.name: sales-service

product-service.name: product-service
