server:
  port: 52001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

swagger:
  enabled: true
  contact-email: guenoun.y@sfeir.com
  contact-name: Youssef Guenoun
  security:
    enabled: false
  enable-try-out-methods: true
  include-patterns: ^(?!.*admin).*$

management:
  context-path: /admin

security:
  basic:
    enabled: false

info:
 stage: step14-solution
 topic: discovery and registry
 service: product-service
 version: 1.1
