debug: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

server:
  port: 9001

swagger:
  title: todolist API
  description: todolist API documentation
  version: 0.0.1
  termsOfServiceUrl: API terms of services URL
  contactName: John Doe
  contactUrl:
  contactEmail:
  license: API License type
  licenseUrl: API License URL


