server:
  port: 9001

auth:
  server:
    resource-id: a1ea4ba4-5b93-40d8-ac4c-f3790dfb3652
    resource-secret: Mw0Z31E_hjr81Gi3LTVlyqFtx7051wBrFJIDPDghVIanOXyR7YFIUBTC6OAnrlnAqtzX1O1qPecjcKcMIads4Q
    authorization-server-endpoints:
      introspect: http://localhost:8080/openid-connect-server-webapp/introspect
  service:
    scopes:
    - api.todo-list-service.v1

swagger:
  enabled: true
  contact-email: guenoun.y@sfeir.com
  contact-name: Youssef Guenoun
  security:
    enabled: true
    implicit-flow:
      authorization-endpoint-url: http://localhost:8080/openid-connect-server-webapp/authorize
      client-id: 7ab1983b-6572-4be9-91a5-f239d7de0b30
    global-scopes:
    -
      name: openid
      description: openid connect scope
    -
      name: profile
      description: user profile scope
    -
      name: api.todo-list-service.v1
      description: product service global scope
  enable-try-out-methods: true
